name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Deploy 🚀
      env:
        API_KEY: ${{ secrets.API_KEY }}
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
